import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Loading from '../components/Loading/loading'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mapeamento Perfil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello World!</h1>
    </div>
  )
}
